export { HomePage } from './Home'
export { NotFoundPage } from './NotFound'
export { LoginPage, RegisterPage } from './Auth'
export { DashboardPage } from './Dashboard'
export { MiniatureDetailPage } from './Detail'
export { PublicBoardPage, PublicMiniatureDetailPage } from './Board'
